version: 2
jobs:
  build:
    working_directory: ~/python-django
    docker:
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:2.7.15
    steps:
      - checkout
      - run:
          command: |
            pip install virtualenv
            virtualenv -p python powtoon
            . powtoon/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "powtoon"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: powtoon_app