# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powtoon', '0002_auto_20190121_0116'),
    ]
    operations = [

    ]

